site_name: Deep RL Course
site_url: https://deeprlcourse.github.io
theme:
  name: material
  custom_dir: overrides
  font:
    text: Ubuntu
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black
      accent: red

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: black
      accent: red
  features:
    - navigation.tabs
    - toc.integrate
    # - navigation.indexes

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
  - tags:
      tags_file: blog/tags.md
  - social

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DeepRLCourse
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/DeepRLCourse
    - icon: fontawesome/brands/telegram
      link: https://t.me/DeepRLCourse

copyright: Made with ❤️ in Robust and Interpretable Machine Learning Lab

nav:
  - Home:
    - index.md
  - Blog:
    - blog/index.md
    - Tags: blog/tags.md
  - Calender:
    - calender/index.md
  - Lectures:
    - lectures/index.md
  - Prerequisites:
    - prerequisites/index.md
    - prerequisites/linear_algebra.md  
  - Recitations:
    - recitations/index.md
  - Workshops:
    - workshops/index.md
  - Homeworks:
    - homeworks/index.md
  - Course Notes:
    - course_notes/index.md
  - Journal Club:
    - journal_club/index.md
  - Poster Session:
    - poster_session/index.md
  - Resources:
    - resources/index.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
