authors:
  arash:
      name: Arash Alikhani
      description: Lead Head TA
      avatar: https://media.licdn.com/dms/image/D4E03AQHn-1E8o-25Kw/profile-displayphoto-shrink_200_200/0/1702016258490?e=2147483647&v=beta&t=x9uAOTg16GKOn2PTPr63Q_BLTDA9tKtxjgEwUc0JZrw